name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - run: cargo fmt -- --check
      - run: clippy -- -D warnings

  check:
    name: Run cargo check with ${{ matrix.rust }} on ${{ matrix.os }}
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - 1.33.0
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@${{ matrix.rust }}
      - run: cargo check

  test:
    name: Run tests with ${{ matrix.rust }} on ${{ matrix.os }}
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - 1.33.0
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@${{ matrix.rust }}
      - run: cargo test
